# Generated by Django 4.0 on 2022-01-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='degree',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='projects',
            field=models.TextField(default='1', max_length=1000),
            preserve_default=False,
        ),
    ]
