# Generated by Django 4.0 on 2022-01-02 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pdf', '0002_profile_degree_profile_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_linked',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='auth.user'),
            preserve_default=False,
        ),
    ]
